# Generated by Django 4.2.7 on 2023-12-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
